# Generated by Django 2.2.2 on 2019-06-24 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_auto_20190624_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
